export enum ActionTypes {
  GET_ALL_ANIME = "GET_ALL_ANIME",
  GET_ANIME_EPISODE = "GET_ANIME_EPISODE",
  SEARCH_ANIME = "SEARCH_ANIME",
  OPEN_SEARCH_ANIME = "OPEN_SEARCH_ANIME",
  CLOSE_SEARCH_ANIME = "CLOSE_SEARCH_ANIME",
}