export enum MutationTypes {
  SET_ALL_ANIME = "SET_ALL_ANIME",
  SET_ANIME_EPISODES = "SET_ANIME_EPISODES",
  SET_SEARCH_ANIME = "SET_SEARCH_ANIME",
  SET_OPEN_RESULT_SEARCH = "SET_OPEN_RESULT_SEARCH",
  SET_CLOSE_RESULT_SEARCH = "SET_CLOSE_RESULT_SEARCH",
}