export enum ActionTypes {
  GET_ALL_MANGA = "GET_ALL_MANGA",
  GET_MANGA = "GET_MANGA",
  SEARCH_MANGA = "SEARCH_MANGA",
  OPEN_SEARCH_MANGA = "OPEN_SEARCH_MANGA",
  CLOSE_SEARCH_MANGA = "CLOSE_SEARCH_MANGA",
}