export enum MutationTypes {
  SET_ALL_MANGA = "SET_ALL_MANGA",
  SET_MANGA = "SET_MANGA",
  SET_SEARCH_MANGA = "SET_SEARCH_MANGA",
  SET_OPEN_RESULT_SEARCH = "SET_OPEN_RESULT_SEARCH",
  SET_CLOSE_RESULT_SEARCH = "SET_CLOSE_RESULT_SEARCH",
}