export enum MutationTypes {
  SET_ALL_MANGA = "SET_ALL_MANGA",
  SET_SEARCH_ANIME = "SET_SEARCH_ANIME",
  SET_OPEN_RESULT_SEARCH = "SET_OPEN_RESULT_SEARCH",
  SET_CLOSE_RESULT_SEARCH = "SET_CLOSE_RESULT_SEARCH",
}